export enum ErrorCode {
  UNKNOWN = 999,
  AUTH_INVALID_DETAIL = 1,
  AUTH_TOKEN_INVALID_ACCESS_TOKEN = 2,
  AUTH_ROLE_INVALID,
  AUTH_TOKEN_INVALID_REFRESH_TOKEN,
  USER_ID_NOT_FOUND,
  USER_ACCOUNT_DISABLED,
  FIELD_NOT_EXISTED,
}
